### ISSUE TITLE
Error in arch arm64

### ISSUE THREAD

**Issue by jlrosende** [containeroo/cloudflare-operator#102]
When I try to run the cloudflare-operator in a kubernetes cluster with arm procesors the image lauch the following error
```bash
exec /manager: exec format error
```
The problem is in the _Dockerfile_, the env `GOARCH=amd64`, so the compilation for arm64 is done in a wrong arch.
```dockerfile
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go
```
**Solution 1:**
Remove the env variable GOARCH
In the file _.goreleaser.yaml_ is defined the arch, so is not necesary set in the _Dockerflie_

_Dockerfile_
```dockerfile
# Build the manager binary
FROM golang:1.18 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
```

**Solution 2:**
Add the arch as argument and set in the _.goreleaser.yaml_ config file

_Dockerfile_
```dockerfile
# Build the manager binary
FROM golang:1.18 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/

# Build
ARG ARCH=amd64
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
```
_.goreleaser.yaml_
```yaml
---
project_name: cloudflare-operator
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}-amd64
      - containeroo/cloudflare-operator:{{ .Tag }}-amd64
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - api
      - controllers
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --build-arg ARCH=amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/cloudflare-operator
      - --label=org.opencontainers.image.source=https://github.com/containeroo/cloudflare-operator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
  - image_templates:
      - ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}-arm64
      - containeroo/cloudflare-operator:{{ .Tag }}-arm64
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - api
      - controllers
    goarch: arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --build-arg ARCH=arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/containeroo/cloudflare-operator
      - --label=org.opencontainers.image.source=https://github.com/containeroo/cloudflare-operator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
docker_manifests:
  - name_template: containeroo/cloudflare-operator:{{ .Tag }}
    image_templates:
      - containeroo/cloudflare-operator:{{ .Tag }}-amd64
      - containeroo/cloudflare-operator:{{ .Tag }}-arm64
  - name_template: ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}
    image_templates:
      - ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}-amd64
      - ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}-arm64
  - name_template: containeroo/cloudflare-operator:latest
    image_templates:
      - containeroo/cloudflare-operator:{{ .Tag }}-amd64
      - containeroo/cloudflare-operator:{{ .Tag }}-arm64
  - name_template: ghcr.io/containeroo/cloudflare-operator:latest
    image_templates:
      - ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}-amd64
      - ghcr.io/containeroo/cloudflare-operator:{{ .Tag }}-arm64
release:
  extra_files:
    - glob: ./crds.yaml
```
