### ISSUE TITLE
cert-manager and cloudflare-operator

### ISSUE THREAD

**Issue by sinist3rr** [containeroo/cloudflare-operator#282]
Hi.
I need to create wildcard certificates using cert-manager, and it has to pass the dns check, so cert-manager should create a temporary TXT record. But cloudflare-operator manages to delete the record before the check is done. 
Is there any workaround for this problem?

**Comment by rxbn** [comment]
Hi @sinist3rr

Thanks for reaching out to us.

In theory, cloudflare-operator should ignore DNS TXT records required by cert-manager:
https://github.com/containeroo/cloudflare-operator/blob/e5658cc1f296bd0b560d0407e32cf2cb9b02d1a8/controllers/zone_controller.go#L130

Please send us the DNS record, which cert-manager creates. Maybe our check is not correct.

Best regards,
-- Robin

**Comment by sinist3rr** [comment]
I checked again.
I'm trying to get a wildcard certificate for a subdomain "demo"
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: wildcard-cloudflare
spec:
   commonName: '*.demo.example.com'
   dnsNames:
   - '*.demo.example.com'
```

cert manager successfully added an entry to cloudflare:
`TXT  _acme-challenge.demo`

After this, in the operator’s logs there is a message
`{"level":"info","ts":"2023-10-25T16:50:17Z","msg":"Deleted DNS record on Cloudflare _acme-challenge.demo.example.com","controller": "zone","controllerGroup":"cloudflare-operator.io","controllerKind":"Zone","Zone":{"name":"example-com"},"namespace":"","name":"example-com","reconcileID ":"bb15290b-ac4f-434e-bd95-69d6b478ee76"}`
